### ISSUE TITLE
Discover pubs through others

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#105]
It would be nice if we could discover other pubs through the follow graph to suggest them as possible connections under the Connections tab.  This will likely need to wait until we can control how many hops we're replicating.

**Comment by KyleMaas** [comment]
AFAICT, it looks like the new (2.0 series of db2 branch - more likely to actually work properly) versions of ssb-conn will support this if we want to turn on the configuration option:

https://github.com/staltz/ssb-conn/blob/4b1808772ab25ec2ebbc639c200b700f5aeaa63f/src/conn-scheduler.ts#L398

**Comment by arj03** [comment]
I disabled the pub discovery on purpose because frankly not a lot of pubs support web sockets.

**Comment by KyleMaas** [comment]
Fair enough.
