### ISSUE TITLE
Something is strange with the auto refresh

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#114]
I'm getting a bunch of Refreshing in the console, about 1 per second and the UI grounds to a halt.

**Comment by KyleMaas** [comment]
Is this on an existing profile or starting from scratch?

**Comment by arj03** [comment]
Existing. 

Seems to happen if you are navigate to lets say profile and go back to public. I added some debug and I could see:

```
adding timer
Refreshing
refreshing from auto timer!
adding timer
Refreshing
refreshing from auto timer!
adding timer
Refreshing
```

**Comment by KyleMaas** [comment]
I'm thinking it must be setting a timer when there already is one.  Since it only tracks one at a time, it would never clear the other one(s).  I'll see what I can do.

**Comment by KyleMaas** [comment]
@arj03 Attempted fixes in #115.  I can't seem to duplicate this problem, so you'll probably need to try it and see if it works.

**Comment by KyleMaas** [comment]
I think #119 would fix this, but it needs to be tested.

**Comment by KyleMaas** [comment]
> Seems to be working much better now

From @arj03 here: https://github.com/arj03/ssb-browser-demo/pull/119#issuecomment-769845708

I'm assuming this can be closed now.
