### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#126]
One of the things that patchbay had that patchwork doesn't, is that if you reply to a thread and the thread receives another reply. The thread will go into the notification. This means you don't have to @ mention people all the time. On the other hand patchwork has a notification for follows which patchbay doesn't. I kind of like that feature as well.

**Comment by KyleMaas** [comment]
Hm.  Looking at the code for Notifications, I guess I never really realized what it did.  I've never had anything pop up in there.  I can't think of a way to do this with a single db2 query, but I guess you could do this through a process like this:

1. All messages with a mention (the way it works now).
2. All messages with an author of yourself.  Not necessarily posts, but also votes.
3. All messages with the same thread root as (1) or (2).
4. Remove messages from the list which are from yourself.

That way, you'd get mentions and updates to threads you've commented or voted on.  Does that make sense as a way to do that, or is there a better way?

**Comment by arj03** [comment]
Yes, but I think you shouldn't include votes, only posts (replies) and then only include messages after you posted a message.

**Comment by KyleMaas** [comment]
I think #143 would mostly take care of this.  Probably won't include follow notifications, though.

**Comment by KyleMaas** [comment]
Do you think we can close this, or do you want me to try to add in follow notifications, too?

**Comment by arj03** [comment]
I'll do the follow notifications once we fix up ssb-friends. I have a plan :-)

**Comment by KyleMaas** [comment]
Perfect.

**Comment by arj03** [comment]
If you want @KyleMaas you can also work on adding notifications for following you.

**Comment by KyleMaas** [comment]
@arj03 I'm assuming we can close this now?

**Comment by arj03** [comment]
Yes, thanks
