### ISSUE TITLE
Console errors re: sodium-chloride

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#132]
These two messages have always been logged to the console when I try to load this:

```
error loading sodium bindings: Cannot find module 'sodium-chloride'
falling back to javascript version.
```

Would be nice if we could find a way to get rid of those so the page doesn't display any errors unless there's an actual error.

**Comment by arj03** [comment]
Yes!

**Comment by KyleMaas** [comment]
This should fix this:

https://github.com/ssb-js/chloride/pull/27

**Comment by KyleMaas** [comment]
Hm.  Somehow this isn't fixed.  Something must still be pulling in an older version of chloride.

@arj03 Could you help me hunt this down please?

**Comment by arj03** [comment]
Try again. Seems to be working for me.

**Comment by KyleMaas** [comment]
That did it.  Thanks!
