### ISSUE TITLE
Restoring feed doesn't work properly, private messages are not properly decoded.

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#14]
There is a problem with restoring feed where the new key does not propagate all the way to ssb-db2, meaning messages are not properly decoded.

_Originally posted by @arj03 in https://github.com/arj03/ssb-browser-demo/issues/13#issuecomment-753521180_

**Comment by KyleMaas** [comment]
Not being an avid user of SSB private messages, does this work if you refresh the page after restoring your key, or does it just not propagate the key through at all?

**Comment by arj03** [comment]
I'll be working on a fix for this. It is one of my top priorities for browser now.
