### ISSUE TITLE
Setup instructions for room server

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#145]
I'm having a hard time figuring out how to add WebSockets to the ssb-room Docker image.  I've tried changing config.js inside of the image.  I've tried rebuilding the image with config.js as part of it (which is likely also necessary because I need another port open).  I've tried linking the config.js of the Docker image to an area in the parent-writable area so I could change it.  I just cannot seem to get it to work.  I'd love to submit a patch to fix https://github.com/staltz/ssb-room/issues/26 but just can't seem to figure out how to do it.

But aside from that, we need some documentation on how to do this in this project as well so people who already have a room or pub server know how to reconfigure to be compatible with ssb-browser-demo.

@arj03 Are there any other differences between your configuration and stock other than that one extra "ws" line in the configuration you posted before?

**Comment by arj03** [comment]
There is. I'll get back to you with that later tonight. The good news is that we are working on rooms 2.0 and I think that should make it a bit easier to enable web sockets by default. It will use the go server instead.

**Comment by KyleMaas** [comment]
Perfect.  Thanks!

**Comment by arj03** [comment]
Here is the diff I'm using: https://gist.github.com/arj03/cedf85cff361ce0f08d151bd7b7d0adb

**Comment by KyleMaas** [comment]
Ah, so it needs ssb-ws pulled in.  I thought that was in there by default.  That's probably what I was doing wrong.  I'll have to give it a try later.  Thanks!

**Comment by KyleMaas** [comment]
That looks a lot better.  Let me see what I can do to put this together into something more user-friendly.

**Comment by KyleMaas** [comment]
Fixed with #149.
