### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#15]
What is the license for this project?

**Comment by arj03** [comment]
https://en.m.wikipedia.org/wiki/Beerware

**Comment by arj03** [comment]
I can add a license file, would that help @KyleMaas? It's stated in package.json

**Comment by KyleMaas** [comment]
Yeah, that'd be great.  It would just make it easier to find.

**Comment by arj03** [comment]
Done

**Comment by KyleMaas** [comment]
Awesome.  Thanks!
