### ISSUE TITLE
Version 4.2.0

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#150]
Hokey smokes!  I know you mentioned doing final cleanup for a new release, but I didn't realize we had 197 commits since the last release.  What else would you like to see done before doing another release?

**Comment by arj03** [comment]
Heh, could you help with a list of all the things that have changed from your side of things since last release? I would like to test if the onboarding screen works on mobile (smaller screen).

**Comment by KyleMaas** [comment]
### New features/enhancements:
* New Channels tab
* New Settings tab
* Themes
* Filter preferences on the Public tab are saved
* New filter for favorite channels
* New filter for channels to hide
* Public messages can now be posted to a channel
* Connections now shows peers by name
* New onboarding screen
* User-friendly Markdown editor
* Profile pages now have "Send Message" buttons
* Channels can now be replied to directly
* Internationalization support
* Japanese translation
* Pirate translation
* Allow for message titles in Public messages
* Autorefresh feature for Public messages
* Include replies to threads in Notifications
* Suggest profile names when typing @ in an editor
* When a user is blocked, we now delete their messages from the database
* When easily available, thread titles are displayed for reply messages
* We now use ssb-social-index and ssb-suggest instead of the old custom profiles index

### Bug fixes:
* Lots of performance optimizations from arj03
* Clicking Disconnect now forgets connections so they don't try to reconnect
* When changing pages, the page title is updated, making browser history useful for back/forward
* Update dependencies
* Multiple fixes for pagination
* Display error to user if they exceed message size limits, rather than just failing on the console
* Get rid of the chloride errors which always showed up on page load

**Comment by arj03** [comment]
So about this. I really want to do a release before this weekend. I'll be doing a talk at fosdem about the browser code :-) This also means that I probably don't want to merge bigger things. Currently I'm working on porting over ssb-friends and using that in browser-core. Andre is doing some testing with abouts to see if we can get that nicer.

**Comment by KyleMaas** [comment]
Good to know.  That'll be nice if we can get a working ssb-friends - I've run into things needing that as a dependency before, although I don't remember exactly where.  Currently working on the "more reactions" issue.  Is there anything else you'd like to see worked on before your talk?

**Comment by KyleMaas** [comment]
Aye aye, cap'n!

**Comment by arj03** [comment]
Another thing I have been wondering is if its possible to include the toast editor like we do with vue so that we don't need to include in the dist bundle. That would save up some time when doing npm run build.

**Comment by KyleMaas** [comment]
Just gave it a quick try.  Does not look like it will function correctly without a bunch of additional work.  The toastui-editor file has dependencies like CodeMirror that it tries to pull in and fails.

**Comment by KyleMaas** [comment]
Did you get a chance to take a look at the Use Offline stuff?

**Comment by arj03** [comment]
I think the use offline will have to wait until after the release

**Comment by KyleMaas** [comment]
Sounds like a plan.

**Comment by KyleMaas** [comment]
Well, we're up to 253 commits not since that last release.

**Comment by arj03** [comment]
Yes, this will be 5.0.0. Coming right up

**Comment by KyleMaas** [comment]
Cool.  Yeah, I suppose with the ssb-friends stuff, a major version bump is probably more appropriate.

**Comment by KyleMaas** [comment]
As a related aside, do you have a link to the SSB talks?  I think I only saw one on the schedule.

**Comment by KyleMaas** [comment]
Heh...might want to change the "We now use ssb-social-index and ssb-suggest instead of the old custom profiles index" part of the 5.0.0 release.  :)

**Comment by arj03** [comment]
Sure, its here https://people.iola.dk/anders/fosdem-talk/. The video should be up tomorrow.

**Comment by arj03** [comment]
> Heh...might want to change the "We now use ssb-social-index and ssb-suggest instead of the old custom profiles index" part of the 5.0.0 release. :)

Right :)
