### ISSUE TITLE
Optimize inlined build

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#158]
The inlined build clocks in at around 22.5MB.  That seems excessive.  About 12.5MB of that comes from the emoji font.  Almost 5MB of that comes from the font on the Floral Garden Bird theme.  The rest of the resources (even the Pirate theme's font) are pretty minimal.  But I'd like to try to optimize this a bit more.

**Comment by arj03** [comment]
I'm all for a smaller font if you can find a good one

**Comment by KyleMaas** [comment]
I was able to save some space on the inlined builds by using an older version of Noto Emoji, but that's about as good as I could do.  Unfortunately, there are not a lot of good options for color emoji fonts with decent codepoint coverage under permissive licenses.
