### ISSUE TITLE
More reactions

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#159]
I really like reactions, sadly we only have 3. It would be really nice with a hover thing where you can select a few more.

**Comment by KyleMaas** [comment]
Which ones would you like?  They just need to be added to this list:

https://github.com/arj03/ssb-browser-demo/blob/master/ui/ssb-msg.js#L75

**Comment by KyleMaas** [comment]
As you can see from that code, I had more options in there before and pared it down a bit so it wasn't so overwhelming.  But there are a few easy choices there if you want them.

**Comment by arj03** [comment]
I think of all those are good, maybe add :rocket: and 🍕 :-)

**Comment by arj03** [comment]
Regarding the overwhelming part then I think that would be solves with a popup or something

**Comment by KyleMaas** [comment]
I was originally trying for a popup, but couldn't find a good elegant way to do that.  I'll give it another try, though.
