### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#165]
A feature I've heard of others using on other social media platforms is the concept of grouping "friends" together (in whatever platform-specific terms they use) into a group that, when clicked on, shows all of the public posts from the folks in that group.  It would be nice if we had a way to do this.  Not private groups, but public groupings solely for the use of the user.  For example, you could have a group called "SSB Developers" which contains users you know who are active SSB developers, so you can click on that group and see all of the most recent posts from them.

I could implement this quite easily on the client side by using localPrefs.  But is there a good way to represent this as an SSB message so that groupings like this could be persistent across client database resets?  Perhaps both a private version only accessible to the user and a public version so others could access this group and import it as well?

**Comment by arj03** [comment]
Yeah that what was I was thinking of earlier. So 💯 this feature :) 

I think the best way for this would be to start by persisting it in local storage. Then we can always figure out the schema for ssb messages once we/you know exactly what to put in them :)
