### ISSUE TITLE
Go to profile by name in right corner

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#173]
So we have this search thingy in the corner, would be nice if you could just do `@Kyle` and have suggestions come so you can go to a profile without known their id.

**Comment by KyleMaas** [comment]
Oh, that's a good idea.

**Comment by KyleMaas** [comment]
I want to wait until we get away from ssb-suggest until trying to tackle this one.  I think we could use a lot of the same code as the Markdown editor's profile suggestion stuff, but that needs to be ported, too.

**Comment by arj03** [comment]
Makes sense. What you can do is based in on top of that PR if you want.

**Comment by KyleMaas** [comment]
Okay.  I think I'll probably just wait, though.  I'd rather develop a solution once.
