### ISSUE TITLE
Autoconnect follows

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#185]
If a "Possible Connection" for a room endpoint pops up and it's someone we're already following, I would think it'd be quite helpful if it automatically connected to them.

**Comment by arj03** [comment]
Think should happen automatically. If not, that is a bug ;)

**Comment by KyleMaas** [comment]
Hm...didn't know it was supposed to do that.  It looks like it *tries*, at least, but I'm not sure it's successful in actually persisting it.  Appears something goofy's going on with your room right now and the connection looks like it's resetting.

**Comment by KyleMaas** [comment]
I'll test it again later.

**Comment by KyleMaas** [comment]
I was able to confirm that this does work.  Closing this issue.
