### ISSUE TITLE
Group tweaks

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#200]
As I alluded to earlier I absolutely loooooooooove groups. So I'm a really heavy user of that feature now. Some things I noticed:
 - Would be good with a loaded indicator
 - Would be nice if you could rename groups
 - Would be nice in the groups view that it shows the latest message, maybe only with time + author for each group
 - The add group should probably be on top

**Comment by KyleMaas** [comment]
> Would be good with a loaded indicator

Can you expand on this a little?  Don't quite understand what you're looking for.

**Comment by arj03** [comment]
When you go to a group, it will just display: (No messages to display) 

Until it actually fetches messages from db

**Comment by KyleMaas** [comment]
Ah, gotcha.
