### ISSUE TITLE
Shrink main dist file

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#219]
Main dist file is currently about 6.9MB (see https://github.com/arj03/ssb-browser-demo/pull/208#issuecomment-776765786).  Let's see if we can shrink that.

**Comment by KyleMaas** [comment]
@arj03 Not finding a whole lot more opportunities to shrink this.  With #221 merged in, do you think we could close this?

**Comment by arj03** [comment]
I have a tool I'd like to use to figure out what is taking this space. So lets keep it open for now.

**Comment by KyleMaas** [comment]
This would help a little:

https://github.com/dweinstein/pull-async-filter/issues/1

**Comment by arj03** [comment]
Now I remember the tool: `npm i -g disc`

# discify dist/js/bundle-ui.js > out.html

![image](https://user-images.githubusercontent.com/350682/107968405-9e8d8700-6fae-11eb-97b1-23a879e5206b.png)

Some of the biggest:

Toast: 1.2mb
Highlight: 1mb
libsodium: 500kb
codemirror: 400kb

It should be possible to disable highlight somehow I think. The gain we get from that package seems rather minimal.

**Comment by arj03** [comment]
Yeah highlight.js comes from ssb-markdown. Maybe add a switch so it can be disabled?

**Comment by arj03** [comment]
Bip39 is 200kb. Wonder where that is used.

**Comment by KyleMaas** [comment]
I checked on Bip39 before.  It's used for mnemonic keys.

**Comment by KyleMaas** [comment]
That's part of where I focused my efforts for minifying before, because I noticed the mnemonic key word lists have a *ton* of whitespace in them.  Part of the reason I've been working on shrinking the release bundle rather than the build bundle.

**Comment by KyleMaas** [comment]
Well, that takes us down to about 3.5MB.  Do you think that's good enough, or is there more you'd like to try to do?

**Comment by arj03** [comment]
I'll close this now. 1mb off compared to last release is pretty good. Thanks for the help with this @KyleMaas :)

**Comment by KyleMaas** [comment]
You're welcome!
