### ISSUE TITLE
Support DHT connections

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#22]
It would be great if connections could be made via DHT like they can with Manyverse.  This way you could direct connect without a room or a pub.

**Comment by arj03** [comment]
Yeah that would be great. Manyverse uses the same ssb conn so should be possible to do what it is doing to make it work. Happy to help review and help if you have questions.

**Comment by KyleMaas** [comment]
Well, I've made an attempt with pull request #23.  It probably needs some more work, because I couldn't get it to actually link up with an instance of Manyverse on my phone.  But I feel like I'm quickly getting out of my depth.

**Comment by KyleMaas** [comment]
This should be pretty doable if this gets merged:

https://github.com/staltz/multiserver-dht/pull/5

**Comment by arj03** [comment]
Sweet!

**Comment by KyleMaas** [comment]
Really struggling with this.  I can get it to look like it works with an old version of hyperswarm-web.  Except it only looks like it works, but it actually doesn't.  If I try to update it, current versions give me the following error when I try to build:

`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (587:0) while parsing (path-to-local-checkout-of-multiserver-dht)/node_modules/reconnecting-websocket/dist/reconnecting-websocket-mjs.js`

I think I'm going to put this down for a bit and come back to it later.  Just not making any progress.

**Comment by KyleMaas** [comment]
Mwahahaha!!!  I got it to work.  Now to figure out how...

**Comment by KyleMaas** [comment]
There we go.  Between the commits I pushed to my add-dht-support branch and this pull request:

https://github.com/staltz/multiserver-dht/pull/5

And this change to reconnecting-websocket:

https://github.com/pladaria/reconnecting-websocket/issues/149

It now works.  Now, it's still a little buggy and has only had limited testing so far.  But I was able to successfully connect from one browser to another on the same computer and pass messages between them.

**Comment by KyleMaas** [comment]
Oh, and I forgot this issue isn't filed under ssb-browser-core.  You need the add-dht-support branch of that for it to work as well.

**Comment by KyleMaas** [comment]
@arj03 We now have pull request #125 which works without manual dependency patching, if you want to try this out.

**Comment by KyleMaas** [comment]
This is mostly just waiting on this at this point:

https://gitlab.com/staltz/ssb-dht-invite/-/issues/2

**Comment by KyleMaas** [comment]
@arj03 Is it possible you could poke @staltz about this:

https://gitlab.com/staltz/ssb-dht-invite/-/issues/2

I would expect it will fix a lot of the problems he's having with Manyverse due to lack of NAT hole punching.  And it's the main thing that's blocking me from getting DHT working in the browser at this point.

**Comment by KyleMaas** [comment]
So, continuing the discussion here, it looks like the initial sync works but some time after that EBT fails trying to claim the invite code a second time, and this happens right after the `method:tunnel,ping is not in the list of allowed methods` error, so I think that error is causing some problems.

**Comment by arj03** [comment]
Yeah if ping is not supported your connection will timeout. This should not be related to DHT, just that with DHT it is easier to trigger. This should now be fixed in ssb-browser-core 9.3.2.

**Comment by KyleMaas** [comment]
Excellent.
