### ISSUE TITLE
Support blog

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#223]
At least show them. It's actually relatively easy because they are just blobs. There is a library [here](https://github.com/ssbc/scuttle-blog). Like the SSBC newsletters is published as a blog.

**Comment by KyleMaas** [comment]
Do you have a good example of a blog message (by ID)?  Doing a query for the one in the README comes back with an empty result set.

**Comment by KyleMaas** [comment]
Found a sample message: `%Kly5qANVcTkqLLoS1f9xClbPjn3EYMoMpaqPFK1WqtE=.sha256`

**Comment by KyleMaas** [comment]
Okay, so it looks like blog message content is just formatted as Markdown within the blob.  That should be easy enough to render.

**Comment by KyleMaas** [comment]
Better test message: `%WSfYoQZLrB0oDhW5rc8lZxmApOgG18Fo81D4DWx9cXU=.sha256`
