### ISSUE TITLE
Forum view

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#228]
> In fact, it’s the first time I use a phpBB in a looooooong time. The UI is… amazing!!!
It has no hidden things, no things that move around based on some open-source-yet-totally-unintuitive algo, it has virtually no client-side JS, it’s got strong, tree-like categories.
> 
> I keep saying it and it bears repeating: ssb needs a UI like this, even if it is just a heuristic view onto the existing posts.

From Daan in `%M2LuCm+C9piUuZDCpKk3uvqWqIprB%2FTisVh7B0+oRns=.sha256`

As a still-active user of old-style fora, I would have to agree with this.  It would make it much easier to browse posts.  And I think it's something that could be implemented without too much difficulty.

**Comment by arj03** [comment]
Yeah, I had an idea of a forum view as well. I think the trick might be to figure out how to group the tags into overall groups and use that as the base.
