### ISSUE TITLE
NotFoundError

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#232]
Well, here's a new one.  This happened when I couldn't get two browser windows to replicate each other through the pub (both browsers were set up to follow each other but weren't actually replicating despite showing sync as complete), so I had them both join the room as well.  They connected to each other and finally synced other others' profiles, but then I started getting a whole bunch of these messages during EBT synced extended contacts from the graph:

```
could not retrive msg: err {type: "NotFoundError", name: "NotFoundError", cause: "Error: NotFound...", message: "Key not found in database [["@BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=.ed25519",5581]]", stack: "NotFoundError: Key not found in database [["@BQXNd… (http://127.0.0.1:8080/js/bundle-ui.js:104310:5)"}
```

This seems to at least roughly correspond to a bunch of these messages showing up in the other browser:

```
invalid message: expected sequence 15248 but got:15247in state:{"id":"%WkRHw498eXWYSCf+NEw9/rophtzK01j31p7D02VTPwc=.sha256","sequence":15247,"timestamp":1611134144910,"queue":[]}, on feed:@p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519
```

**Comment by arj03** [comment]
I actually this bug should be fixed now. There was a problem in EBT. Is it ok if I close this and you open again if you still see it?

**Comment by KyleMaas** [comment]
Yeah, that's fine.  I haven't been tinkering enough lately to really hit a lot of these oddball bugs, so I don't know if this has been fixed or not.
