### ISSUE TITLE
invalid message: expected sequence 2 but got:1

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#234]
Figured I might as well file an issue for this so we can collect together information about it.  I'm getting this fairly consistently now in a lot of different situations and I don't understand enough about what it's doing to be able to track it down.

Steps to reproduce:
1. Start a new profile (open it in a private browser window or something).
2. Leave everything in the onboarding screen as defaults and click Get Started.

That's all it takes for me to trigger that error.

**Comment by KyleMaas** [comment]
Also, can you give me any pointers as to where to start debugging this?

**Comment by arj03** [comment]
The error is from [validate](https://github.com/ssb-js/ssb-validate). So either [here](https://github.com/ssb-ngi-pointer/ssb-db2/blob/b7522decb7c87803791d155c574a38956ceb5571/db.js#L151) or [here](https://github.com/ssb-ngi-pointer/ssb-db2/blob/b7522decb7c87803791d155c574a38956ceb5571/db.js#L180). It must be somehow related to how ssb-browser-core does the partial replication.

**Comment by KyleMaas** [comment]
How long do you think until https://github.com/ssb-ngi-pointer/ssb-subset-replication is usable?

**Comment by arj03** [comment]
We are aiming for May

**Comment by KyleMaas** [comment]
@arj03 Probably could use your help on this one, too.  Having a hard time making any progress at all on this.

**Comment by arj03** [comment]
Nice find. I can reproduce this problem.

**Comment by arj03** [comment]
Fixed with this [commit](https://github.com/arj03/ssb-browser-core/commit/c9268d63ee0eb77f82e7e85225aae57628fc48ea)

**Comment by KyleMaas** [comment]
Hokey smokes!  That's all it took?  The difference it makes to have the knowledge of how it all works...

I'll give it a test here in a few minutes.

**Comment by arj03** [comment]
Yeah, a bit of a funny bug. Very nice to have it fixed though, might have caused other kinds of wierd problems.

**Comment by arj03** [comment]
I'll close this. I made a release with these changes :-)

**Comment by KyleMaas** [comment]
Sounds good.  Just finished doing a write-up on one-way follows.

Yep, looks like that fixed it.  Thanks!

**Comment by arj03** [comment]
Sweet! Thanks for reporting this.
