### ISSUE TITLE
Test with ggfeed-v1 messages

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#257]
See `%MiW/j32viwG2/rtMCwgXWASPPc9FxSTYCCqrgxZKVFk=.sha256`

https://github.com/cryptix/js-gabbygrove

**Comment by arj03** [comment]
Please note that a new feed format is quite a bit change in more or less the whole stack ;-) I would like to get to a point where we can do that easier, like EBT is prepared for it now. I think we will need multiple feeds in first. I am personally very excited about [bamboo](https://github.com/pietgeursen/bamboo-rs) (note it has a wasm port).

**Comment by cryptix** [comment]
+1 to what Anders said. And hile we are here... :)

ps: While I would love for gabby grove to see adoption, I also heard that cbor libs **with** canonical (integers) mode are not as _off the shelve_ across languages as I would have liked and thought. Therefore even if bamboo has _a bit more_ custom requirements there it might be worthwhile. 

pps: I made half a decoder for it in [go](https://git.sr.ht/~cryptix/go-bamboo) and it would be pretty easy to add to go-ssb but without stack support in JS-land I don't see a need to hurry.

ppps: there are some interesting issues on the bamboo spec repo, too. I'd wager we might want to cut a v2 of it, reconsider the hash function and sizes and maybe replace stlv with tfk (which we already use in groups) along the way.

**Comment by KyleMaas** [comment]
Oooh, bamboo does indeed look very nice.  Hadn't seen that before.  I do wish there was an MIT-licensed version, though.

**Comment by KyleMaas** [comment]
I'm going to go ahead and close this, then, since this is likely to change a lot before we actually need to look at it.
