### ISSUE TITLE
Refactor ssb-singleton into core

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#267]
That way other applications build on core could use this.

**Comment by KyleMaas** [comment]
Glad to see you working on this.  I was just about to start on this and was at the "thinking through how best to do it" stage.

**Comment by KyleMaas** [comment]
Realized one place that ssb-singleton is not modularized well is in its dependence on `localprefs`.

**Comment by arj03** [comment]
This is now done :)

**Comment by KyleMaas** [comment]
Nice.  That looks great!
