### ISSUE TITLE
Validate message ID before trying to navigate to it

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#270]
Just tried to navigate to a thread by ID, but there was a typo in the ID I copied which made the message ID invalid.  Had me puzzled as to why I couldn't see it.  Would be nice to warn the user that they're trying an invalid message ID and it will never show up.

**Comment by KyleMaas** [comment]
Is there any existing functionality that could validate a message ID or would we be better off just using a regular expression for now?

**Comment by arj03** [comment]
There sure is: https://github.com/ssb-js/ssb-ref :)

**Comment by KyleMaas** [comment]
Perfect.  Why I figured I'd ask before tackling this.
