### ISSUE TITLE
When replying to a thread, refresh the Thread page

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#271]
When you reply to a thread from the Thread page, the reply does not always show up until you refresh the page.  We should definitely show the new message immediately.  (I'm thinking it would also be a good idea to check for new messages in that thread in case someone replied before you so you can see if your new message might somehow be taken out of context, so maybe a full refresh is in order.)

**Comment by arj03** [comment]
Nice find

**Comment by KyleMaas** [comment]
I can no longer duplicate this problem.  But I was able to consistently duplicate it before, so I think I'm going to try to implement a workaround for it.
