### ISSUE TITLE
Moving ssb-singleton to core somehow triggers popup blocker

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#272]
Chromium clearly doesn't like something about ssb-browser-demo now that singleton has been moved to core.  For some reason, and this makes no sense to me right now, center-clicking links is now triggering Chromium's popup blocker where it didn't before.  Disregarding the popup blocker and trying again results in it opening the tab, which crashes with the following error:

```
bundle-ui.js:118419 Uncaught DOMException: Blocked a frame with origin "http://127.0.0.1:8080" from accessing a cross-origin frame.
```

This happens despite the fact that the original was, in fact, opened from the same origin.  Ctrl-clicking does the same thing and so does right-clicking and using the popup context menu's open new tab function.  I have not tried refreshing to see if I can duplicate this, but I did want to at least log as much about this as I could first.

And, again, this makes no sense to me.  In both cases, singleton is in the bundle file, so it's not like it's coming from a different origin.

**Comment by arj03** [comment]
I wonder if that is something that has changed in chrome 89?

**Comment by KyleMaas** [comment]
Considering I'm running Chromium 88, I doubt it.  :)

Besides, I don't believe I've updated Chromium since it was working.  AFAIK the only thing that has changed is ssb-browser-demo.

**Comment by KyleMaas** [comment]
I will note that refreshing the page seems to have cleared up the problem, at least for now.  I will keep watching for this and see if I can figure out how to duplicate it.

**Comment by KyleMaas** [comment]
Had this happen again.

**Comment by KyleMaas** [comment]
Have you seen this at all?  I haven't run into this again since I've gotten back into it.

**Comment by arj03** [comment]
Never, seeing this I'll just close this and you can open if it happens again.

**Comment by KyleMaas** [comment]
Yeah, sounds good.
