### ISSUE TITLE
Realtime status

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#28]
Would be really nice if there was some kind of indication of what it's doing outside of just the little status indicator next to Connections and the browser's console.  It'd be awesome if, in the Connections list, there was a progressbar next to peers when they were doing EBT.

**Comment by arj03** [comment]
Progressbar for EBT is not so easy, you don't really know what the latest is. Secondly when you are in EBT mode things should be really fast. What would be great though is some indicator when doing initial sync (not in connections) that shows a progress bar as you say. This could use the these numbers:

```
"totalPartial": 436,
  "profilesSynced": 436,
  "contactsSynced": 436,
  "messagesSynced": 436,
  "totalFull": 1,
  "fullSynced": 1
```

**Comment by KyleMaas** [comment]
Is there a way to know how many profiles/contacts/messages will be synced when the sync process starts so a percentage can be calculated?  Because from what I understand the totalPartial, profilesSynced, contactsSynced, and messagesSynced all seem to be indications of how much has been completed, not how much will be completed.

**Comment by arj03** [comment]
Not really, but the number of things to do should be a fine approximation. I mean follow my main profiles means you have to download 3x436 "things" so just keeping track of how many of those you have done out of all should create a fine progress bar I think.
