### ISSUE TITLE
RAW buttons are non-obvious

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#291]
* Had to look at the code to figure out why RAW was showing up on posts - there is no tooltip or anything explaining it other than a single word.  Thought initially maybe it was an indicator that the post could be rendered without formatting or something.
* It doesn't show up as a button or change the cursor when you mouse over it.
* Unless you're looking at the console, clicking it seemingly does nothing.
* Position within a post is dependent on whether or not the post has a channel tag.  For posts without one, it's positioned on the right side.  For posts with a channel tag, the RAW is pushed to the left and no longer lines up with anything.

**Comment by arj03** [comment]
Oh yeah, this was mainly because I was debugging something related to threads, forks and replies. I fixed a few things there. I've always liked the ability to view the raw message in clients. And agree that all of the points above would make it a lot easier.

**Comment by KyleMaas** [comment]
So...a question.  What does RAW view do that right-clicking the message and going to "View source" does not?

**Comment by arj03** [comment]
Lol true, I totally forgot about that :) Will remove

**Comment by KyleMaas** [comment]
Sounds good.  Easier to remove redundancy than fix it.  :)
