### ISSUE TITLE
Thread view is broken

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#292]
Clicking on a thread link shows the thread as a single message - "undefined".  Happens with every thread I've tried.  Clicking RAW results in:

```
{
  "key": "",
  "value": {
    "content": {}
  }
}
```

**Comment by KyleMaas** [comment]
Threads also seems to be broken.  I reckon it's likely due to the same underlying problem.

**Comment by arj03** [comment]
Strange. Havn't seen that one before. Did it help to reload?

**Comment by KyleMaas** [comment]
Nope.  Even after a cache clear refresh, it's still doing the same thing.

**Comment by KyleMaas** [comment]
Okay, I'm going to have to correct that.  It did the same thing initially, but then I typed up that reply and when I switched back to it, it worked.

**Comment by KyleMaas** [comment]
So maybe it just wasn't working while it was doing a sync?  Because I think in both cases when it wasn't working it was trying to sync.

**Comment by arj03** [comment]
It could be that if you got a lot of new messages that it was busy indexing.

**Comment by KyleMaas** [comment]
Could be.  Probably shouldn't just be displaying "undefined" while it's loading.
