### ISSUE TITLE
Update vue editor

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#298]
Hey @KyleMaas 

I noticed that the Vue editor has a new major release that is quite a bit smaller. I was wondering if that would be something you would be up for upgrading?

**Comment by KyleMaas** [comment]
I could probably take that on.

**Comment by KyleMaas** [comment]
Land sakes...this is quite a change.  I was doing a bunch of stuff with the cursor position before and they completely changed the API for that.  This may take me a bit longer than I thought.
