### ISSUE TITLE
Minor things with new toast ui

### ISSUE THREAD

**Issue by arj03** [arj03/ssb-browser-demo#303]
There is a small css error on profile page in the input field. The header is too large for the input. @KyleMaas 

I also has this error in console: this.editor.remove is not a function. That problem seems to be fixed on master, but sadly no new release.

**Comment by KyleMaas** [comment]
Can you show me a screenshot?  It looks fine here.

Also, where are you seeing the remove error?

**Comment by arj03** [comment]
The error was in the console. Ah, the profile is only showing the problem if the console is filling 50% of the screen. With that closes it work fine.

**Comment by KyleMaas** [comment]
What triggered the console error, though?  I grepped through the codebase and couldn't find a line that said `this.editor.remove`.

**Comment by arj03** [comment]
This one https://github.com/nhn/tui.editor/commit/999b9e22750ed64302a2880fce2e1fbcb99ba250

**Comment by KyleMaas** [comment]
Ah, so it's an upstream problem.  Gotcha.
