### ISSUE TITLE
Error if profile doesn't have a description

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#305]
```
Uncaught TypeError: Cannot read property 'matchAll' of undefined
    at showProfile (bundle-ui.js:148339)
    at tryToLoadProfile (bundle-ui.js:148377)
    at bundle-ui.js:148386
```

Stems from here:

https://github.com/arj03/ssb-browser-demo/blob/a1274fdf25a8cb3557d20779578d4fa5be663290/ui/profile.js#L657

**Comment by arj03** [comment]
I don't see a showProfile anywhere in this repo? Not even if I grep bundle-ui.js?

Another thing that is really strange, is why that line uses `this` and not `self`.

**Comment by KyleMaas** [comment]
I think that was in an old version from when I had that corrupted git clone I had to redo, so the trace is no longer valid.  But the problematic part of the code is still present in the current master revision.

**Comment by KyleMaas** [comment]
As for why it uses `this` and not `self`, I don't know.
