### ISSUE TITLE
Cannot read property 'partialReplication' of null

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#39]
Getting the following exception:

```
vue.min.js:6 TypeError: Cannot read property 'partialReplication' of null
    at Object.SSB.syncFeedFromLatest (bundle-ui.js:40)
    at a.downloadMessages (bundle-ui.js:93041)
    at He (vue.min.js:6)
    at HTMLButtonElement.n (vue.min.js:6)
    at HTMLButtonElement.Yr.o._wrapper (vue.min.js:6)
```

This happens if I:
1. Starting with a new profile, add a connection to the Hermies room (http://hermiesroom.staltz.com/).
2. Follow @6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519
3. Click "Download Latest Messages for User"

This seems to happen because in SSB.syncFeedFromLatest(), SSB.getPeer() returns null.

**Comment by KyleMaas** [comment]
Actually, IIRC a similar exception occurs during step 2 above:

```
syncing feeds
Uncaught TypeError: Cannot read property 'partialReplication' of null
    at bundle-core.js:217
    at bundle-core.js:62999
    at bundle-core.js:48290
    at bundle-core.js:48186
    at drain (bundle-core.js:67051)
    at ReadStream.<anonymous> (bundle-core.js:67068)
    at ReadStream.emit (bundle-core.js:29502)
    at endReadableNT (bundle-core.js:16467)
    at Item.run (bundle-core.js:47117)
    at drainQueue (bundle-core.js:47087)
```

**Comment by arj03** [comment]
Right, you are connected to a peer that doesn't support partial replication. It shouldn't crash though. A lot of this partial replication stuff is just for testing mostly. In about 3 months time we will be implementing a proper solution for partial replication as part of the ngi pointer grant we are doing.

**Comment by KyleMaas** [comment]
Could we get it to fall back to full replication if partial was unsupported (under the assumption that there will probably be servers running for quite a while that don't support it)?  If so, where would I look to do that?

**Comment by KyleMaas** [comment]
Apparently getPeer() only treats peers where `cp.data.type != 'room'` as "good peers".  So it's actively ignoring pubs in that, which falls back to `Object.values(SSB.net.peers).flat()`, which contains nothing if a room is the only thing you're connected to.

**Comment by arj03** [comment]
Ah yes, room peers don't store any data. There probably needs a lot more error handling of this. Maybe combined with the connectioned function we talked about earlier.

**Comment by KyleMaas** [comment]
So...wondering how this relates to #38?  Because I would love to be able to use old-style rooms in ssb-browser-demo, at least until new-style rooms are implemented, but I'm lost as to why they don't work.  It sure looks like you had them working at one point in time, or at least made significant progress toward it.

**Comment by arj03** [comment]
They are working. The problem here seems to be that you are only connected to the room and no peers that can give you data. So basically these kinds of things where you expect rpc to be available should be wrapped in a SSB.connected, and then maybe connected should make sure that you are connected to something which is not a room.

**Comment by KyleMaas** [comment]
If I connect a room, I would expect normally it would display a list of Possible Connections.  But when I try connecting to a room, either the built-in one or Hermies, it doesn't seem to display anything or, indeed, attempt any network activity at all.

(For that matter, I'd think that if you were connected to a pub it might display other pubs in Possible Connections as well, but it doesn't seem to be doing that either.)

**Comment by KyleMaas** [comment]
Starting a new profile, if I connect to the default room without connecting to anything else, I do see a WebSockets connection going out, but it doesn't show anything in Possible Connections.

**Comment by arj03** [comment]
There are probably no other peers to connect to. The way I was testing this was that I added the browser room to my patchwork, then it could see my main profile.

**Comment by KyleMaas** [comment]
Okay.  Now I can see your browser.  Does the Hermies connection not work because the invite is a net: invite instead of a wss: invite?

`net:hermiesroom.staltz.com:8008~shs:W18NyiHagiiVE4/jm2sxzqQqIwmUw2p9pKZ0lHH9OXA=:SSB+Room+PSK3TLYC2T86EHQCUHBUHASCASE18JBV24=`

**Comment by arj03** [comment]
Yes exactly :)

Browser only support ws or wss (ssl)

**Comment by arj03** [comment]
Probably would be a good idea to warn the user if they tried a net: one? ;)

**Comment by KyleMaas** [comment]
I can probably do that.

**Comment by KyleMaas** [comment]
See #58

**Comment by KyleMaas** [comment]
Okay, so I have another question: does stock Scuttlebot support WebSockets, or is different server software needed?  Or is it a plugin?

**Comment by arj03** [comment]
It is supported by [default](https://github.com/ssb-js/multiserver/blob/main/plugins/ws.js). You just need to enable it. My rooms server is configured as following:

```
connections: {
    incoming: {
      net: [{ port: 8888, host: "0.0.0.0", scope: "public", transform: "shs" }],
      ws: [{ port: 9999, host: "::", scope: "public", transform: "shs", external: ["between-two-worlds.dk"], key: "/etc/letsencrypt/live/between-two-worlds.dk/privkey.pem", cert: "/etc/letsencrypt/live/between-two-worlds.dk/cert.pem" }],
    },
    outgoing: {
      net: [{transform: 'shs'}],
    },
  },
```

**Comment by KyleMaas** [comment]
I guess what I'm wondering is if there a good way to transform an input net: invite into a workable guess at a wss: invite?  That way, if someone input a net: address we don't support, we could suggest they try "X" and see if it works.

**Comment by KyleMaas** [comment]
#59 fixes both of my test cases above.
