### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#42]
There are a few settings I think would be helpful to add:

* Number of hops to replicate.
* Storage limit for blobs (assuming we can get ssb-blobs-purge going at some point).
* Visual theme.
* Ability to set CAPS.
* Any other settings we want to add.

Is there a preferred spot, visually, to try to put this?  Maybe a gear icon to the right of Connections?

**Comment by KyleMaas** [comment]
Oh, I just noticed the screenshot on the repo homepage shows a Settings tab, and it's pretty much exactly where I was figuring it might go.  Except it's spelled out "Settings", whereas I'm not sure if there's space for that now with "Notifications" in there.

**Comment by arj03** [comment]
Right, it was there before. I removed it when I was trying to make things fit on mobile. Adding it there again would be fine at least for desktop.

**Comment by KyleMaas** [comment]
See #47 and #49.  Only thing that doesn't accomplish is the storage limit for blobs, and I haven't been able to get ssb-blobs-purge working yet, so it's kind of pointless to add the setting.

**Comment by arj03** [comment]
I'll close this as it seems to be implemented now. Thanks :)
