### ISSUE TITLE
Votes/reactions in the Channel view

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#45]
When looking at the posts in a channel (by clicking a channel link, for example, from either a post or the Channels tab), it does not appear that votes are being processed correctly.  I removed them from being viewed in #44, but even before that, they appeared to be shown as posts instead of being attached to the relevant post as feedback.

**Comment by arj03** [comment]
They seem to be working fine here. I had a problem with votes that seems to have been because there was a problem with the indexes. I'll try to narrow it down.

**Comment by arj03** [comment]
[This](https://github.com/ssb-ngi-pointer/jitdb/pull/87) was the problem I was seeing. Lets see if it fixes your problem once its merged :)

**Comment by arj03** [comment]
Can you confirm that this is no longer a problem?

**Comment by KyleMaas** [comment]
It does appear it's working now.  If I navigate to a popular channel, I can see messages with votes.
