### ISSUE TITLE
expected matching length at end, expected:13937, was:12856 on block:65536 at offset:441668

### ISSUE THREAD

**Issue by Powersource** [arj03/ssb-browser-demo#5]
This seems similar to but not exactly like https://github.com/arj03/ssb-browser-demo/issues/3

```
Error: expected matching length at end, expected:13937, was:12856 on block:65536 at offset:441668 6 bundle-core.js:1573:579
    getRecord moz-extension://9dfe66b8-7680-43b2-ba1f-08159866ebc5/js/bundle-core.js:1573
    _next moz-extension://9dfe66b8-7680-43b2-ba1f-08159866ebc5/js/bundle-core.js:1581
    resume moz-extension://9dfe66b8-7680-43b2-ba1f-08159866ebc5/js/bundle-core.js:1581
    _ready moz-extension://9dfe66b8-7680-43b2-ba1f-08159866ebc5/js/bundle-core.js:1581
    A moz-extension://9dfe66b8-7680-43b2-ba1f-08159866ebc5/js/bundle-core.js:1577
    A moz-extension://9dfe66b8-7680-43b2-ba1f-08159866ebc5/js/bundle-core.js:1577
```

I think feeds might have completely stopped loading for me now. Not sure if I did anything weird, except reload the page (in different tabs) a bunch of times maybe because of this/other bugs.

Also running this in the webextension which is a few commits back so might be fixed already. Either way I'm guessing I'll need to nuke my db?

**Comment by arj03** [comment]
Yes I fixed a few bugs related to this. Please use latest version 😊

**Comment by arj03** [comment]
Also for nuking there is the SSB.removeDB()

**Comment by Powersource** [comment]
I nuked my db and merged in the new updates, new version published on mozilla. Closing this since it's hopefully fixed.
